---
title: "Assignment_b01"
author: "Marc Wettengel"
date: "03/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Function

The function I've created tells you how many grams of CO$_2$ are emitted per 1 kilometer of driving for either a petrol or diesel car. The two pieces of information needed are the miles per gallon (US gallon) and if your car has a petrol or diesel internal combustion engine. 

```{r}
#'  Amount of CO$_2$ emitted
#'  
#'  This functions estimates the amount of CO$_2$ emitted per kilometer driven 
#'  based on the miles per gallon (US gallon) and the fuel type of your car. 
#'
#' @param x Miles per gallon (measured in US gallons)
#' @param petrol Variable to indicate if engine of car uses petrol or diesel fuel
#'
#' @return Grams of CO2 emitted, on average, per kilometer of driving
#' @export 
#'
#' @examples 
#' co2emission(25, petrol = TRUE)
#' co2emissions(42, petrol = FALSE)
co2emission <- function(x, petrol = TRUE){
  if(!is.numeric(x)) { 
    stop('This function only works for numeric input!\n',
         'You have provided an object of class: ', class(x)[1])
  }
  if(petrol == TRUE) {
    result <- 8887/x
    paste("Your petrol car emmits, on average,", round(result/1.609, 2), "grams of co2 per km driven")
  } else {
    result2 <- 10180/x
    paste("Your diesel car emmits, on average,", round(result2/1.609, 2), "grams of co2 per km driven")
  }
}
```

### Function Examples

```{r, error = TRUE}
# Comparing that although two cars may have same mpg, 
#   emissions will differ based on engine fuel statement 
co2emission(32, petrol = TRUE)
co2emission(32, petrol = FALSE)

# Using a non-numeric input will not work
co2emission("car", petrol = FALSE)

# A vector will work, as long as the cars are all the same fuel type.
cars <- c(22, 33, 44)
co2emission(cars, petrol = TRUE)
```

### Testing Function

```{r}
# A petrol car should not have same Co2 emissions as diesel car with same mpg
expect_no_match(co2emission(33, petrol = TRUE), co2emission(33, petrol = FALSE))
# 33 mpg for a petrol car should equal 167.37
expect_equal(co2emission(33, petrol = TRUE), "Your petrol car emmits, on average, 167.37 grams of co2 per km driven")
# Should bring about an error message
expect_error(co2emission("dragon", petrol = TRUE))

test_that("Functionality test for co2emisson function", {
  expect_no_match(co2emission(33, petrol = TRUE), co2emission(33, petrol = FALSE))
  expect_equal(co2emission(33, petrol = TRUE), "Your petrol car emmits, on average, 167.37 grams of co2 per km driven")
  expect_error(co2emission("dragon", petrol = TRUE))
})
```



```{r}

```

